name: Build mobile apps

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm install
      - name: Build web
        run: npm run build
      - name: Setup Capacitor Android
        run: |
          npm install @capacitor/android
          npx cap add android
          npx cap sync android
      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quizapp-android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Setup Capacitor iOS
        if: runner.os == 'macOS'
        run: |
          npm install @capacitor/ios
          npx cap add ios
          npx cap sync ios
      - name: Build iOS IPA
        if: runner.os == 'macOS'
        run: |
          cd ios/App
          xcodebuild -scheme App -configuration Release -archivePath App.xcarchive archive
          xcodebuild -exportArchive -archivePath App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath .
      - name: Upload IPA
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: quizapp-ios-ipa
          path: ios/App/*.ipa
